package com.arunge.el.attribute;

public enum EntityAttribute {
    NAME,
    CLEANSED_NAME,
    ALIASES,
    CLEANSED_ALIASES,
    UNIGRAMS,
    BIGRAMS,
    ACRONYM,
    METAPHONE,
    TFIDF_WORDS,
    FULL_EMB,
    WINDOW_EMB,
    FULL_EMB_TFIDF,
    WINDOW_EMB_TFIDF,
    TOPIC_25,
    TOPIC_50,
    TOPIC_100,
    TOPIC_200,
    TOPIC_300,
    TOPIC_400,
    TOPIC_500,
    ENTITY_TYPE,
    INREF_ENTITIES,
    OUTREF_ENTITIES,
    COREF_ENTITIES,
    OUT_LINKS,
    IN_LINKS,
    ENT_IB_DIST,
    ENT_CN_IB_DIST,
    GOLD_LABEL,
    GOLD_NER
}
